cache:
  pip: true
  timeout: 1000

language: python

python:
  - 3.7
  - 3.8-dev

matrix:
  fast_finish: true

notifications:
  email: false

# repo branches to test
branches:
  - master

install:
  - pip install -U pip wheel --quiet
  - pip install --upgrade setuptools --quiet
  - pip install pytest
  - pip install pytest-coverage
  - pip install coveralls
  - pip install .[dev]

script:
  - pytest --cov basecam --cov-report html

after_success:
  - coveralls
