language: python

python:
  - 3.7

dist: trusty

matrix:
  include:
    - python: 3.8-dev
      dist: xenial
      sudo: true
      before_install:
        - pip install git+https://github.com/astropy/astropy@master
  allow_failures:
    - python: 3.8-dev

notifications:
  email: false

# repo branches to test
branches:
  - master

install:
  - pip install -U pip wheel --quiet
  - pip install --upgrade setuptools --quiet
  - pip install pytest
  - pip install pytest-coverage
  - pip install coveralls
  - pip install .[dev]

script:
  - pytest --cov basecam --cov-report html

after_success:
  - coveralls
