name: Test

on:
  push:
    branches: [main]
    paths-ignore:
      - '*.md'
      - '*.rst'
  pull_request:
    branches: [main]
    paths-ignore:
      - '*.md'
      - '*.rst'

jobs:
  build:
    runs-on: ubuntu-24.04

    env:
      OBSERVATORY: APO

    strategy:
      fail-fast: false
      matrix:
        python-version: ['3.8', '3.9', '3.10', '3.11', '3.12', '3.13']

    steps:
      - uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@v5
        with:
          enable-cache: true

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.13'

      - name: Install package
        run: |
          uv sync --no-dev

      - name: Test with pytest
        run: |
          uv pip install pytest pytest-cov pytest-asyncio pytest-mock asynctest pytest-sugar
          uv run pytest

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v5
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: ./coverage.xml
